import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const discovery = readFileSync(new URL('./native-session-discovery.ts', import.meta.url), 'utf8')
const feed = readFileSync(new URL('./native-session-feed.ts', import.meta.url), 'utf8')
const claim = readFileSync(new URL('./native-session-claim.ts', import.meta.url), 'utf8')
const continuation = readFileSync(new URL('./native-session-continuation.ts', import.meta.url), 'utf8')
const observer = readFileSync(new URL('./components/native-session-observer.tsx', import.meta.url), 'utf8')
const sessionHome = readFileSync(new URL('./components/native-session-home.tsx', import.meta.url), 'utf8')
const sessionNavigation = readFileSync(new URL('./session-first-navigation.css', import.meta.url), 'utf8')
const standalone = readFileSync(new URL('./components/standalone-universal-workspace.tsx', import.meta.url), 'utf8')
const main = readFileSync(new URL('./main.tsx', import.meta.url), 'utf8')

assert.ok(discovery.includes('listGlobalSessions(config).catch(() => client.listSessions(config))'), 'native discovery must retain global-list fallback')
assert.ok(discovery.includes('listStatuses(config).catch'), 'status enrichment must remain non-fatal')
assert.ok(discovery.includes('export type NativeSessionRef'), 'Session-first must define one explicit native Session operation identity')
assert.ok(discovery.includes('machineID: string'), 'native Session identity must include its machine')
assert.ok(discovery.includes('agentID: string'), 'native Session identity must include its harness')
assert.ok(discovery.includes('sessionID: string'), 'native Session identity must preserve the harness-owned Session id')
assert.ok(discovery.includes('key: `${machineID}:${record.key}`'), 'render/controller identity must not collide across machines')
assert.ok(discovery.includes('agentId: record.agentId'), 'native Session targets must stay scoped to their owning harness')
assert.equal(discovery.includes('createTask('), false, 'discovery must not synthesize a Task/Conversation')
assert.equal(discovery.includes('launch('), false, 'discovery must not acquire a Session writer')

assert.ok(feed.includes('mergeLatestMessagePage'), 'native Session tail refresh must reuse HR3 message identity merging')
assert.ok(feed.includes('prependOlderMessagePage'), 'native Session history paging must reuse HR3 older-page merging')

assert.ok(continuation.includes('client.claimSession(target.config, target.directory, target.sessionID)'), 'ACP continuation must claim the exact native Session through an explicit Session boundary')
assert.equal(continuation.includes('listModels('), false, 'Session-first continuation must not expose model discovery as its ownership primitive')
assert.ok(claim.includes('`/session/${encodeURIComponent(sessionID)}/claim`'), 'claim transport must call the dedicated native Session claim endpoint')
assert.equal(claim.includes('listModels('), false, 'native Session claiming must no longer use model discovery at the client boundary')
assert.equal(claim.includes('createSession('), false, 'claim transport must never create a replacement Session')
assert.equal(claim.includes('createTask('), false, 'claim transport must not synthesize a Task/Conversation')
assert.equal(claim.includes('launch('), false, 'claim transport must not enter the Task launcher')
assert.ok(continuation.includes('target.backend === "opencode"'), 'OpenCode must retain its direct same-Session continuation path')
assert.equal(continuation.includes('createSession('), false, 'continuation probing must never create a replacement Session')
assert.equal(continuation.includes('createTask('), false, 'continuation probing must not synthesize a Task/Conversation')
assert.equal(continuation.includes('launch('), false, 'continuation probing must not enter the Task launcher')

assert.ok(observer.includes('import { TaskDeskConversation } from "./taskdesk-conversation"'), 'native Session continuation must reuse the HR3 chat surface')
assert.ok(observer.includes('<TaskDeskConversation'), 'native Session controller must render the existing HR3 chat')
assert.equal(observer.includes('TaskDeskMessageContent'), false, 'native Session controller must not create a second message renderer')
assert.ok(observer.includes('probeNativeSessionContinuation(target)'), 'external Sessions must remain observe-only until the safe continuation probe succeeds')
assert.ok(observer.includes('api.sendPrompt(target.config, target.sessionID, text, target.directory)'), 'continuation must send to the exact same native Session id')
assert.equal(observer.includes('createSession('), false, 'same-Session continuation must never create a replacement Session')
assert.equal(observer.includes('createTask('), false, 'same-Session continuation must not synthesize a Task/Conversation')
assert.equal(observer.includes('launch('), false, 'same-Session continuation must not use the Task launcher')

assert.ok(sessionHome.includes('discoverMachineNativeSessions'), 'the Sessions home must use native discovery rather than Task data')
assert.ok(sessionHome.includes('nativeSessionSurfaceTarget(item.machine.id, item.machine.config, item.record)'), 'opening a Session must carry its machine id into the controller')
assert.ok(sessionHome.includes('SESSION_HOME_REFRESH_MS = 30_000'), 'native Session discovery must stay off the existing 10s Conversation workspace poll')
assert.ok(sessionHome.includes('COLLAPSED_PROJECT_SESSION_COUNT = 5'), 'each Project must start with a bounded Session list like the reference harness workspace browser')
assert.ok(sessionHome.includes('function projectGroups('), 'the Sessions browser must group native Sessions by Project/workspace rather than inventing dashboard buckets')
assert.ok(sessionHome.includes('const key = `${item.machine.id}\\u0000${directory}`'), 'Project grouping must retain machine plus canonical Session directory identity')
assert.ok(sessionHome.includes('group.sessions.slice(0, COLLAPSED_PROJECT_SESSION_COUNT)'), 'collapsed Projects must keep older Sessions out of the initial navigation surface')
assert.ok(sessionHome.includes('aria-expanded={expanded}'), 'Project Session expansion must expose its state accessibly')
assert.ok(sessionHome.includes('className={`hr-native-session-row${working ? " active" : ""}`}'), 'Sessions must render as compact navigation rows')
assert.equal(sessionHome.includes('Active now'), false, 'the Sessions browser must not split the same Project into synthetic Active/Recent dashboard sections')
assert.equal(sessionHome.includes('taskClient'), false, 'the Sessions home must not depend on Task/Conversation storage')

assert.ok(sessionNavigation.includes('grid-template-columns: repeat(4, minmax(0, 1fr))'), 'mobile Session-first navigation must keep four bounded destinations')
assert.ok(sessionNavigation.includes('(pointer: coarse) and (min-width: 600px) and (max-height: 640px)'), 'four-destination Session navigation must also apply to phone short-landscape')
assert.ok(sessionNavigation.includes('box-sizing: border-box'), 'mobile navigation width must include safe-area padding and borders')
assert.ok(sessionNavigation.includes('max-width: 100vw'), 'mobile navigation must never exceed the visual viewport')
assert.ok(sessionNavigation.includes('.hr-mobile-nav > button'), 'Session-first navigation must bound each destination independently')

assert.ok(standalone.includes('<ConversationWorkspace'), 'the validated HR3 Conversation workspace must remain mounted')
assert.ok(standalone.includes('primarySection === "sessions" ? <NativeSessionsWorkspace'), 'Sessions must be an additive section, not a replacement shell')
assert.ok(standalone.includes('<NativeSessionObserver'), 'the integrated Sessions detail must reuse the native Session controller')
assert.ok(standalone.includes('<NativeSessionHome'), 'the integrated workspace must expose native Sessions directly')
assert.equal(standalone.includes('SessionFirstPreviewPage'), false, 'the product integration must not promote the isolated preview shell')

assert.ok(main.includes('<StandaloneUniversalWorkspace'), 'the validated HR3 default workspace must remain the product entrypoint')
assert.equal(main.includes('NativeSessionObserver'), false, 'main.tsx must not bypass the HR3 workspace host')

console.log('session-first regression guards passed')
