import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const machineClient = readFileSync(new URL('./machineClient.ts', import.meta.url), 'utf8')
const discovery = readFileSync(new URL('./native-session-discovery.ts', import.meta.url), 'utf8')
const feed = readFileSync(new URL('./native-session-feed.ts', import.meta.url), 'utf8')
const claim = readFileSync(new URL('./native-session-claim.ts', import.meta.url), 'utf8')
const prompt = readFileSync(new URL('./native-session-prompt.ts', import.meta.url), 'utf8')
const stop = readFileSync(new URL('./native-session-stop.ts', import.meta.url), 'utf8')
const continuation = readFileSync(new URL('./native-session-continuation.ts', import.meta.url), 'utf8')
const observer = readFileSync(new URL('./components/native-session-observer.tsx', import.meta.url), 'utf8')
const sessionHome = readFileSync(new URL('./components/native-session-home.tsx', import.meta.url), 'utf8')
const sessionNavigation = readFileSync(new URL('./session-first-navigation.css', import.meta.url), 'utf8')
const standalone = readFileSync(new URL('./components/standalone-universal-workspace.tsx', import.meta.url), 'utf8')
const main = readFileSync(new URL('./main.tsx', import.meta.url), 'utf8')

assert.ok(machineClient.includes('export async function listMachineProjects'), 'Session-first must read the daemon Project catalog through the machine client')
assert.ok(machineClient.includes('path: "/v1/projects"'), 'desktop Project discovery must stay machine-scoped')
assert.ok(machineClient.includes('machineBaseUrl(config)}/v1/projects'), 'browser/mobile Project discovery must stay machine-scoped')
assert.ok(machineClient.includes('projectCache'), 'Project discovery should retain the same short transient-network grace as machine discovery')

assert.ok(discovery.includes('listGlobalSessions(config).catch(() => client.listSessions(config))'), 'native discovery must retain global-list fallback')
assert.ok(discovery.includes('listStatuses(config).catch'), 'status enrichment must remain non-fatal')
assert.ok(discovery.includes('export type NativeSessionRef'), 'Session-first must define one explicit native Session operation identity')
assert.ok(discovery.includes('machineID: string'), 'native Session identity must include its machine')
assert.ok(discovery.includes('agentID: string'), 'native Session identity must include its harness')
assert.ok(discovery.includes('sessionID: string'), 'native Session identity must preserve the harness-owned Session id')
assert.ok(discovery.includes('transport: agent.transport'), 'native Session discovery must retain the transport that defines writer ownership semantics')
assert.ok(discovery.includes('key: `${machineID}:${record.key}`'), 'render/controller identity must not collide across machines')
assert.ok(discovery.includes('agentId: record.agentId'), 'native Session targets must stay scoped to their owning harness')
assert.ok(discovery.includes('record.transport === "acp" && record.writerOwned !== true'), 'metadata-only ACP Sessions must remain observe-only unless this daemon explicitly knows it owns the writer')
assert.ok(discovery.includes('writerOwned?: boolean'), 'daemon-created ACP Sessions need an explicit ownership fact so the UI never asks the user to claim them twice')
assert.ok(discovery.includes('supportedStopCapability(record.stopCapability)'), 'Stop must be gated by the explicit Session capability contract')
assert.ok(discovery.includes('abortSupported: agent.capabilities?.abort === true'), 'Stop must also require the harness abort capability')
assert.ok(discovery.includes('modelsSupported: agent.capabilities?.models === true'), 'native Session model controls must be capability-gated from machine discovery')
assert.equal(discovery.includes('createTask('), false, 'discovery must not synthesize a Task/Conversation')
assert.equal(discovery.includes('launch('), false, 'discovery must not acquire a Session writer')

assert.ok(feed.includes('mergeLatestMessagePage'), 'native Session tail refresh must reuse HR3 message identity merging')
assert.ok(feed.includes('prependOlderMessagePage'), 'native Session history paging must reuse HR3 older-page merging')
assert.ok(feed.includes('normalizeNativeSessionTurns'), 'native Session chat must reuse v3 logical-turn normalization before rendering ACP envelopes')
assert.ok(feed.includes('limit,\n    false'), 'native Session transcript reads must stay on the mature v3 authority instead of switching to ACP replay after claim')

assert.ok(continuation.includes('client.claimSession(target.config, target.directory, target.sessionID)'), 'ACP continuation must claim the exact native Session through an explicit Session boundary')
assert.equal(continuation.includes('listModels('), false, 'Session-first continuation must not expose model discovery as its ownership primitive')
assert.ok(claim.includes('`/session/${encodeURIComponent(sessionID)}/claim`'), 'claim transport must call the dedicated native Session claim endpoint')
assert.equal(claim.includes('listModels('), false, 'native Session claiming must no longer use model discovery at the client boundary')
assert.equal(claim.includes('createSession('), false, 'claim transport must never create a replacement Session')
assert.equal(claim.includes('createTask('), false, 'claim transport must not synthesize a Task/Conversation')
assert.equal(claim.includes('launch('), false, 'claim transport must not enter the Task launcher')
assert.ok(continuation.includes('target.backend === "opencode"'), 'OpenCode must retain its direct same-Session continuation path')
assert.equal(continuation.includes('createSession('), false, 'continuation probing must never create a replacement Session')
assert.equal(continuation.includes('createTask('), false, 'continuation probing must not synthesize a Task/Conversation')
assert.equal(continuation.includes('launch('), false, 'continuation probing must not enter the Task launcher')

assert.ok(prompt.includes('clientRequestId'), 'native Session prompts must carry a durable client request id')
assert.ok(prompt.includes('loadPendingNativeSessionPrompt'), 'native Session prompt retries must recover unresolved request ids after reload')
assert.ok(prompt.includes('target.machineID'), 'native Session prompt persistence must be machine-scoped')
assert.ok(prompt.includes('target.agentID'), 'native Session prompt persistence must be harness-scoped')
assert.ok(prompt.includes('target.sessionID'), 'native Session prompt persistence must preserve the native Session id')
assert.ok(prompt.includes('`/session/${encodeURIComponent(target.sessionID)}/prompt`'), 'native Session prompts must use the idempotent daemon operation endpoint')
assert.ok(prompt.includes('existing.text !== normalized || !sameModel(existing.model, requestedModel)'), 'a different prompt or model must not jump ahead of unresolved native delivery')
assert.ok(prompt.includes('variant: pending.model?.variant || undefined'), 'native Session prompt retry must preserve the selected effort/variant')
assert.equal(prompt.includes('createSession('), false, 'native Session prompt transport must never create a replacement Session')
assert.equal(prompt.includes('createTask('), false, 'native Session prompt transport must not synthesize a Task/Conversation')
assert.equal(prompt.includes('launch('), false, 'native Session prompt transport must not use the Task launcher')

assert.ok(stop.includes('clientRequestId'), 'native Session Stop must use a durable client request id')
assert.ok(stop.includes('operationToken'), 'Stop idempotency must be scoped to the current native turn rather than the Session forever')
assert.ok(stop.includes('target.machineID'), 'Stop persistence must be machine-scoped')
assert.ok(stop.includes('target.agentID'), 'Stop persistence must be harness-scoped')
assert.ok(stop.includes('target.sessionID'), 'Stop persistence must preserve the native Session id')
assert.ok(stop.includes('`/session/${encodeURIComponent(target.sessionID)}/stop`'), 'Stop must use the daemon native Session operation endpoint')
assert.equal(stop.includes('api.abort('), false, 'Session-first Stop must not bypass the daemon ownership/idempotency boundary')
assert.equal(stop.includes('createTask('), false, 'native Session Stop must not synthesize a Task/Conversation')

assert.ok(observer.includes('import { TaskDeskConversation } from "./taskdesk-conversation"'), 'native Session continuation must reuse the HR3 chat surface')
assert.ok(observer.includes('<TaskDeskConversation'), 'native Session controller must render the existing HR3 chat')
assert.equal(observer.includes('TaskDeskMessageContent'), false, 'native Session controller must not create a second message renderer')
assert.ok(observer.includes('probeNativeSessionContinuation(target)'), 'Sessions requiring writer acquisition must remain observe-only until the safe continuation probe succeeds')
assert.ok(observer.includes('target.requiresExplicitClaim ? "observe" : "ready"'), 'ACP discovery must not infer writable state from missing external metadata')
assert.ok(observer.includes('if (writeState !== "observe") return'), 'an already-running Session must still allow an explicit ownership claim after client reload')
assert.ok(observer.includes('api.listStatuses(target.config, target.directory)'), 'the open Session must reconcile lightweight activity status instead of freezing its discovery snapshot')
assert.ok(observer.includes('sendNativeSessionPrompt(target, text, selectedModel)'), 'continuation must send model and effort through the idempotent native Session operation path')
assert.ok(observer.includes('taskClient.listAgentModels(target.config, target.agentID)'), 'native Session model discovery must use the read-only daemon agent catalog')
assert.equal(observer.includes('/config/providers'), false, 'native Session model discovery must not use a user Session as an ownership primitive')
assert.ok(observer.includes('const pending = loadPendingNativeSessionPrompt(target)'), 'a lost-response prompt must restore its text and model selection after reload')
assert.ok(observer.includes('stopNativeSession(target, activeTurnToken)'), 'Stop must flow through the durable native Session mutation path')
assert.ok(observer.includes('onStop={target.canStop && writable ? stop : undefined}'), 'the existing HR3 Stop control must be capability- and ownership-gated')
assert.ok(observer.includes('messages[index]?.info.role === "user"'), 'Stop retries must retain one turn identity across assistant streaming updates')
assert.equal(observer.includes('api.sendPrompt('), false, 'Session-first must not bypass daemon prompt idempotency with the legacy direct API')
assert.equal(observer.includes('api.abort('), false, 'Session-first must not bypass daemon Stop safety with the legacy direct API')
assert.equal(observer.includes('createSession('), false, 'same-Session continuation must never create a replacement Session')
assert.equal(observer.includes('createTask('), false, 'same-Session continuation must not synthesize a Task/Conversation')
assert.equal(observer.includes('launch('), false, 'same-Session continuation must not use the Task launcher')

assert.ok(sessionHome.includes('discoverMachineNativeSessions'), 'the Sessions home must use native discovery rather than Task data')
assert.ok(sessionHome.includes('listMachineProjects(machine.config)'), 'the Sessions home must enrich native cwd data from the daemon Project catalog')
assert.ok(sessionHome.includes('nativeSessionSurfaceTarget(item.machine.id, item.machine.config, item.record)'), 'opening a Session must carry its machine id into the controller')
assert.ok(sessionHome.includes('SESSION_HOME_REFRESH_MS = 30_000'), 'native Session discovery must stay off the existing 10s Conversation workspace poll')
assert.ok(sessionHome.includes('COLLAPSED_PROJECT_SESSION_COUNT = 5'), 'each Project must start with a bounded Session list like the reference harness workspace browser')
assert.ok(sessionHome.includes('function catalogProject('), 'Session cwd attribution must use one explicit ProjectCatalog matcher')
assert.ok(sessionHome.includes('project.machineId === machineID && pathContains(project.path, directory)'), 'Project attribution must remain machine-scoped and path-based')
assert.ok(sessionHome.includes('.sort((left, right) => normalizedPath(right.path).value.length'), 'nested Projects must choose the most specific catalog path')
assert.ok(sessionHome.includes('`${item.machine.id}\\u0000project:${project.id}`'), 'catalogued Project groups must use the daemon stable Project id')
assert.ok(sessionHome.includes('`${item.machine.id}\\u0000directory:${nativeDirectory}`'), 'uncatalogued Sessions must retain exact machine + native-directory fallback identity')
assert.ok(sessionHome.includes('group.sessions.slice(0, COLLAPSED_PROJECT_SESSION_COUNT)'), 'collapsed Projects must keep older Sessions out of the initial navigation surface')
assert.ok(sessionHome.includes('aria-expanded={expanded}'), 'Project Session expansion must expose its state accessibly')
assert.ok(sessionHome.includes('className={`hr-native-session-row${working ? " active" : ""}`}'), 'Sessions must render as compact navigation rows')
assert.equal(sessionHome.includes('Active now'), false, 'the Sessions browser must not split the same Project into synthetic Active/Recent dashboard sections')
assert.equal(sessionHome.includes('taskClient'), false, 'the Sessions home must not depend on Task/Conversation storage')

assert.ok(sessionNavigation.includes('grid-template-columns: repeat(4, minmax(0, 1fr))'), 'mobile Session-first navigation must keep four bounded destinations')
assert.ok(sessionNavigation.includes('(pointer: coarse) and (min-width: 600px) and (max-height: 640px)'), 'four-destination Session navigation must also apply to phone short-landscape')
assert.ok(sessionNavigation.includes('box-sizing: border-box'), 'mobile navigation width must include safe-area padding and borders')
assert.ok(sessionNavigation.includes('max-width: 100vw'), 'mobile navigation must never exceed the visual viewport')
assert.ok(sessionNavigation.includes('.hr-mobile-nav > button'), 'Session-first navigation must bound each destination independently')

assert.ok(standalone.includes('<ConversationWorkspace'), 'the validated HR3 Conversation workspace must remain mounted as temporary compatibility')
assert.ok(standalone.includes('primarySection === "sessions" ? <NativeSessionsWorkspace'), 'the product shell must render the integrated native Sessions workspace')
assert.ok(standalone.includes('useState<"conversations" | "sessions">("sessions")'), 'Session-first product entry must open native Sessions by default')
assert.equal(standalone.includes('useState<"conversations" | "sessions">("conversations")'), false, 'legacy Conversations must never regain the default product entry')
assert.equal(standalone.includes('if (primarySection === "sessions") {\n        setPrimarySection("conversations")'), false, 'Android Back from the Sessions home must not silently demote the user into legacy Conversations')
const sessionsNavIndex = standalone.indexOf('<span>Sessions</span>')
const conversationsNavIndex = standalone.lastIndexOf('<span>Conversations</span>')
assert.ok(sessionsNavIndex >= 0 && conversationsNavIndex >= 0 && sessionsNavIndex < conversationsNavIndex, 'mobile primary navigation must lead with Sessions rather than legacy Conversations')
assert.ok(standalone.includes('<NativeSessionObserver'), 'the integrated Sessions detail must reuse the native Session controller')
assert.ok(standalone.includes('<NativeSessionHome'), 'the integrated workspace must expose native Sessions directly')
assert.equal(standalone.includes('SessionFirstPreviewPage'), false, 'the product integration must not promote the isolated preview shell')

assert.ok(main.includes('<StandaloneUniversalWorkspace'), 'the integrated HR3 host must remain the product entrypoint')
assert.equal(main.includes('NativeSessionObserver'), false, 'main.tsx must not bypass the HR3 workspace host')

console.log('session-first regression guards passed')
